import { flightType } from "../../../utils/types";

export const flights: flightType[] = [
  {
    id: 1,
    image: "/images/newyork.jpg",
    departure: "Jakarta",
    deprt_initial: "CGK",
    arrival: "New York",
    arrival_initial: "JFK",
    flight_price: "$282",
    initial_price: "$820",
    discount: "60% OFF",
  },
  {
    id: 2,
    image: "/images/paris.jpg",
    departure: "Athena",
    deprt_initial: "ATH",
    arrival: "Paris",
    arrival_initial: "CDG",
    flight_price: "$381",
    initial_price: "$820",
    discount: "60% OFF",
  },
  {
    id: 3,
    image: "/images/nigeria.jpg",
    departure: "London",
    deprt_initial: "LDR",
    arrival: "Lagos",
    arrival_initial: "LAG",
    flight_price: "$300",
    initial_price: "$820",
    discount: "60% OFF",
  },
  {
    id: 4,
    image: "/images/istanbul.jpg",
    departure: "Bangkok",
    deprt_initial: "BKK",
    arrival: "Istanbul",
    arrival_initial: "IST",
    flight_price: "$234",
    initial_price: "$820",
    discount: "60% OFF",
  },

  {
    id: 5,
    image: "/images/germany.jpg",
    departure: "Seoul",
    deprt_initial: "CDG",
    arrival: "Munich",
    arrival_initial: "MUN",
    flight_price: "$336",
    initial_price: "$820",
    discount: "60% OFF",
  },
  {
    id: 6,
    image: "/images/southafrica.jpg",
    departure: "Paris",
    deprt_initial: "CDG",
    arrival: "Cape Town",
    arrival_initial: "CCT",
    flight_price: "$238",
    initial_price: "$820",
    discount: "60% OFF",
  },
];
